config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  get 'join', to: 'articles#join'

  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # resources :book

    resources :users, except: [:new] do
      resources :cars, only: [:index, :new, :create] 
    end

    resources :users do
      resources :books, only: [ :new, :create] 
    end
    
    resources :users do
      resources :articles, only: [ :new, :create] 
    end

    resources :cars, :only => [:show, :update, :destroy, :edit]
    resources :books, only: [:index, :show, :update, :destroy, :edit]
    resources :sessions, only: [:index, :show, :update, :edit, :new], except: [:destroy]
    resources :articles
    resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord


   belongs_to :user

   has_many :article_categories
   has_many :categories, through: :article_categories
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  


  def index
    # @articles = Article.all
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)

    @q2 = Article.ransack(params[:q])

    @category = Category.all

  end  


  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create

      @article = Article.new(article_params)
      @article.user = current_user

      @article.category_ids = article_params[:category_ids]
      @article.save!

      
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to @article

    else
      render :new, status: :unprocessable_entity


    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  def join 

    @category = Category.all
    @article = Article.all


  end

  private
  def article_params

    params.require(:article).permit(:title, :body, :status, :category_ids => [])

  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%=  flash[:notice]%>

<%= search_form_for @q, url: articles_path do |f| %> 

<%= f.label :title_cont %>
<%= f.search_field :title_cont %>
<br>

<%= f.label :"Search title body" %>
<%= f.search_field :body_cont %>
<br>

<%= f.label :created_at_gteq %>
<%= f.text_field :created_at_gteq %>
<br>

<%= f.label :created_at_lteq %>
<%= f.text_field :created_at_lteq %>
<br>



<%= f.submit %>

<%end%>





<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <p>It was published at <%=article.created_at.utc%></p>
    </li>
  <% end %>
</ul>






<%= link_to "New Article", new_article_path %>

app/views/articles/join.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
        <%= @article %>
      <p>It was published at <%=article.created_at.utc%></p>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

 <div>
    <%= form.label :category %><br>
       <%= form.collection_select(:category_ids, Category.all, :id, :name,
    { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size:3 }) %>
  


  </div>

  <div>
    <%= form.submit %>
  </div>

<div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

<% end %>

app/views/articles/search.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <p>It was published at <%=article.created_at.localtime%></p>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<%# <%= render flash[:notice]%> %>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>