config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  get 'join', to: 'articles#join'

  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # resources :book

    resources :users, except: [:new] do
      resources :cars, only: [:index, :new, :create] 
    end

    resources :users do
      resources :books, only: [ :new, :create] 
    end
    
    resources :users do
      resources :articles, only: [ :new, :create] 
    end

    resources :cars, :only => [:show, :update, :destroy, :edit]
    resources :books, only: [:index, :show, :update, :destroy, :edit]
    resources :sessions, only: [:index, :show, :update, :edit, :new], except: [:destroy]
    resources :articles
    resources :categories, except: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase}

    has_many :books
    has_many :cars
    has_many :articles, dependent: :destroy

    validates :name, presence: true, uniqueness: {case_sensitive: false}, 
                length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update]

    def index 
    
    @user = User.all
    
    @users = User.paginate(page: params[:page], per_page: 5)
    
    @user2 = User.find_by(id: 1)
    @car2 = Car.find_by(id: 5)
    end

    def create 

        @user = User.new(user_params)

        if @user.save
            flash[:notice] = "Welcome #{@user.name} you have successfully signed up"
            redirect_to users_path
        else
            render :new
        end
    end

    def show

 

    end

    def new
        @user = User.new

        
    end

    def edit

     
    end

    def update 
    
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end
    end


    def destroy
        @user = User.find_by(email: current_user.email)
        @user.destroy
        session[:user_id] = nil
        flash[:notice] = "User id and all the associated articles have been destroyed"
        redirect_to articles_path
    end




    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password, :user_id)
    end

    def set_user
        @user = User.find(params[:id])
    end

    

end

app/helpers/users_helper.rb
module UsersHelper



      
end

app/views/users/_form.html.erb
<% http_method = @user.new_record? ? "POST" : "PATCH" %>
<% action_url = @user.new_record? ? users_url : user_url(@user) %>

<form action="<%=action_url%>" method="POST">
     <input type="hidden" name="_method" value="<%= http_method %>">


    <label for="name">Name</label>
    <input id="name" type="text" name = user[name]></input>
    <br>
  
    <label for="email">Email</label>
    <input id="email" type="text" name = user[email]></input>
    <br>
  
    <label for="password">Password</label>
    <input id="password" type="password" name = user[password]></input>
    <br>
    
    <input id="submit" type="submit" value="<%=  @user.new_record? ? "Sign up" : "Update account"%>"></input>
    <br>



</form>

app/views/users/_navbar.html.erb
    <% if logged_in? %>
        <li><%= button_to "Sign out", logout_path, method: :delete %></li>
        <% else %>
    <li><%= link_to "Log in", login_path %></li>
    <% end %>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users Names</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.name, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <%= link_to "New Category", new_category_path, class: "btn btn-outline-success" %>
            <%= link_to "New Article", new_article_path, class: "btn btn-outline-success"  %>
            <% if logged_in? %>
              <% if user == current_user %>
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline`-info" %>
              <% end %>
             
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<%= flash[:alert] %>

<%= render 'form'%>

app/views/users/show.html.erb
<%= flash[:notice] %>

<h1> <%= @user.email %> </h1>

<%= gravatar_for @user, size: 200%>

<%=link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info"%>
<%=link_to "Create article", articles_path, class: "btn btn-outline-info"%>

<%= button_to "Destroy User", user_path(@user), method: :delete%>